module riscv_core(Reg_output,address,number,jump,rst,clk);
input rst,clk,jump;
input [31:0] address,number;
output [31:0] Reg_output;
wire [4:0] rd,rs1,rs2;
wire RegWrite,ALUsrc,flag;
wire [6:0] opcode,funct7;
wire [2:0] alu_opcode,funct3;
wire [31:0] read_data1,read_data2,imm_out,operand2,alu_result,instr,pc_out,fetch_address;
pc_reg A1 (pc_out,jump,rst,clk);
address_sel A2 (fetch_address,jump,address,pc_out);
instr_mem A3 (instr,address,number,fetch_address);
assign opcode = instr[6:0];
assign rd = instr[11:7];
assign funct3 = instr[14:12];
assign rs1 = instr[19:15];
assign rs2 = instr[24:20];
assign funct7 = instr[31:25];
imm_gen A4 (imm_out,instr);
control_unit A5 (RegWrite,ALUsrc,opcode);
register_file A6 (Reg_output,read_data1,read_data2,alu_result,rd,rs1,rs2,RegWrite,rst,clk);
alu_src_mux A7 (operand2,imm_out,read_data2,ALUsrc);
alu_control A8 (alu_opcode,flag,funct3,funct7,opcode);
ALU_RISCV A9 (alu_result,read_data1,operand2,alu_opcode,flag);
endmodule